title: Jekyll Learning Site
description: Just playing with Jekyll
author: Claudie
email: claudielarouche@gmail.com
theme: minima

# Optional: Add social links
minima:
  social_links:
    - github: claudielarouche
    - linkedin: claudie-larouche  
  include_footer: custom

include:
  - assets
