title: Claudie Larouche
description: A website demonstrating my projects and featuring articles I wrote
author: Claudie Larouche
email: claudielarouche@gmail.com
theme: minima

include:
  - assets

minima:
  hide_site_feed_link: true
